name: CI/CD Pipeline

on: [push, pull_request] # Runs on every push or PR

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest # You can specify a version like 1.1.4

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test
